

# Some ir codes
IR_CODES:dict[str, str] = {
    "3B": "Power",
    "A1": "Power ON",
    "6C": "Power OFF",
    "3C": "Menu",
    "30": "Help",
    "3D": "ESC",
    "49": "Enter",
    "58": "Pointer: Up",
    "59": "Pointer: Down",
    "5A": "Pointer: Left",
    "5B": "Pointer: Right",
    "5C": "Pointer: Right-up",
    "5D": "Pointer: Left-up",
    "5E": "Pointer: Right-down",
    "5F": "Pointer: Left-down",
    "68": "Page Up",
    "69": "Page Down",
    "51": "1 or IRIS",
    "52": "2",
    "53": "3",
    "54": "4",
    "55": "5 or Volume",
    "4A": "Auto",
    "6B": "InputA/InputB or WallShot",
    "4E": "input A",
    "43": "Comp1(Computer) or Comp1/Comp2 or Component",
    "67": "Comp/EasyMP or Source or SourceSearch",
    "44": "Comp2 or input B or PC",
    "45": "S-Video",
    "46": "Video or Video1/Video2",
    "40": "BNC or D or HDMI2",
    "4F": "S-Video/Video",
    "1D": "DVI or DVI/HDMI",
    "4D": "D-RGB or HDMI or HDMI1",
    "1E": "EasyMP",
    "47": "Freeze or Still",
    "28": "E-Zoom +",
    "29": "E-Zoom -",
    "3E": "A/V Mute",
    "3F": "Color Mode",
    "4B": "Pattern",
    "20": "Aspect",
    "4C": "Reserved",
    "6A": "Memory",
    "61": "Memory (1)",
    "62": "Memory 2",
    "63": "Memory 3",
    "64": "Memory 4",
    "65": "Memory 5",
    "66": "Memory 6",
    "60": "Preset",
    "27": "PinP",
    "2A": "Focus +",
    "2B": "Focus - or Focus",
    "2C": "LensShift +",
    "2D": "LensShift - or LensShift",
    "2E": "Zoom +",
    "2F": "Zoom - or Zoom",
    "56": "Volume +",
    "57": "Volume -",
    "50": "EFFECT or Pointer",
    "1F": "Preview",
    "70": "0(10 Key)",
    "71": "1(10 Key)",
    "72": "2(10 Key)",
    "73": "3(10 Key)",
    "74": "4(10 Key)",
    "75": "5(10 Key)",
    "76": "6(10 Key)",
    "77": "7(10 Key)",
    "78": "8(10 Key)",
    "79": "9(10 Key)",
    "7A": ". (10 Key)",
    "6D": "Source(OEM)",
    "6F": "Quick Setup or Screen Fit",
    "7B": "Keystone +",
    "7C": "Keystone -",
    "7D": "Brightness or Brightness +",
    "7E": "Brightness -",
    "7F": "Contrast or Contrast +",
    "80": "Contrast -",
    "81": "Color Temp.",
    "82": "Flesh Tone",
    "83": "1Dγ",
    "84": "User Button",
    "85": "USB Display or USB",
    "86": "Slideshow",
    "87": "Sharpness",
    "88": "Default",
    "89": "RGBCMY",
    "8A": "LAN or LAN/USB",
    "8F": "ID or ID+HELP",
    "90": "ID+0",
    "91": "ID+1",
    "92": "ID+2",
    "93": "ID+3",
    "94": "ID+4",
    "95": "ID+5",
    "96": "ID+6",
    "97": "ID+7",
    "98": "ID+8",
    "99": "ID+9",
    "8B": "Lens Iris",
    "8C": "Super Res",
    "8D": "Frame Int",
    "8E": "HDMI Link",
    "9A": "Aspect Normal",
    "9B": "Anamorphic",
    "9C": "H Squeeze",
    "A0": "Split",
    "9D": "2D/3D",
    "9E": "2D",
    "9F": "3D",
    "A5": "Auto Iris",
    "A2": "WirelessHD",
    "A3": "SDI",
    "D0": "iPod Control",
    "D1": "Play",
    "D6": "Backward",
    "D7": "Forward",
}
