

# Some keycodes have multiple meanings, those are both mentioned with "or" inbetween
KEY_CODES = {
    "02": "Standby",
    "03": "Menu",
    "04": "Help",
    "05": "ESC",
    "16": "Enter",
    "35": "Up",
    "36": "Down",
    "37": "Left",
    "38": "Right",
    "14": "Auto",
    "48": "Source or SourceSearch",
    "10": "Comp1/2 or Comp/EasyMP",
    "11": "Video/S-Video or BNC/Video",
    "41": "Computer",
    "42": "Video",
    "12": "Freeze",
    "15": "A/V Mute",
    "13": "Blank",
    "1A": "Pattern",
    "21": "Volume +",
    "22": "Volume -",
    "23": "Sync +",
    "24": "Sync -",
    "25": "Tracking +",
    "26": "Tracking -",
    "31": "Brightness +",
    "32": "Brightness -",
    "33": "Contrast +",
    "34": "Contrast -",
    "06": "VKeystone +",
    "07": "VKeystone -",
    "08": "HKeystone +",
    "09": "HKeystone -",
    "39": "Zoom + or Zoom Boot",
    "3A": "Zoom -",
    "1B": "Wide",
    "1C": "Tele",
    "0A": "Focus + or Focus Boot",
    "0B": "Focus -",
    "0C": "LensShift +",
    "0D": "LensShift -",
    "6A": "WallShot",
    "6E": "Quick Setup or Screen Fit",
    "0E": "Lens",
}